apiVersion: batch/v1
kind: Job
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: jobcheck
        image: docker.io/stevenacoffman/jobcheck
        command:
          - /go/bin/jobcheck
        args:
        - sentinel
        - 30
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          exec:
            command:
            - /go/bin/jobcheck
            args:
              - filehealth
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsUser: 10001
          runAsGroup: 10001
        volumeMounts:
          - name: tempdir
            mountPath: "/tmp"
      volumes:
      - name: tempdir
        emptyDir: {}